[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "ayasetan", email = "529157057@qq.com"},
]
dependencies = [
    "prestring>=0.9.0",
    "pyyaml>=6.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
